apiVersion: apps/v1
kind: Deployment
metadata:
  name: pendig-seguridad-ms-sas-generator-nodejs-deployment
  namespace: ns-pendigital-seguridad
  labels:
    app: pendig-seguridad-ms-sas-generator-nodejs-deployment
    domain: ns-pendigital-seguridad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pendig-seguridad-ms-sas-generator-nodejs-deployment
  template:
    metadata:
      labels:
        app: pendig-seguridad-ms-sas-generator-nodejs-deployment
        domain: ns-pendigital-seguridad
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azuspccdckv
      hostAliases:
        - ip: '172.17.21.30'
          hostnames:
            - 'tal1055vip'
        - ip: '172.17.21.31'
          hostnames:
            - 'tal1059vip'
        - ip: '172.17.21.46'
          hostnames:
            - 'tal1055'
        - ip: '172.17.21.149'
          hostnames:
            - 'tal1059'
        - ip: '10.33.126.30'
          hostnames:
            - 'pal2100vip'
        - ip: '10.33.126.31'
          hostnames:
            - 'pal2101vip'
        - ip: '10.33.126.28'
          hostnames:
            - 'pal2100'
        - ip: '10.33.126.29'
          hostnames:
            - 'pal2101'
        - ip: '10.33.126.33'
          hostnames:
            - 'prdracp2000'
        - ip: '10.33.126.34'
          hostnames:
            - 'prdracp2000'
        - ip: '10.33.126.32'
          hostnames:
            - 'prdracp2000'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - pendigital
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 80
      #         podAffinityTerm:
      #           labelSelector:
      #             matchExpressions:
      #               - key: app
      #                 operator: In
      #                 values:
      #                   - pendig-seguridad-ms-sas-generator-nodejs-deployment
      #           topologyKey: "topology.kubernetes.io/zone"
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: "topology.kubernetes.io/zone"
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: pendig-seguridad-ms-sas-generator-nodejs-deployment
      tolerations:
        - key: 'app'
          operator: 'Equal'
          value: 'pendigital'
          effect: 'NoSchedule'
      containers:
        - name: pendig-seguridad-ms-sas-generator-nodejs-deployment
          image: azeupvprddvoacr01.azurecr.io/NAME_ARTIFACT:VERSION
          volumeMounts:
            - name: secrets-store
              mountPath: '/mnt/secrets-store'
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 600Mi
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: ms-pendigital-configmap
                  key: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-pendigital-configmap
                  key: port
            - name: EVENT_HUB_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: logstash-configmap
                  key: ent-hub-connection-queue
            - name: CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: logstash-configmap
                  key: consumer-group
            - name: EVENT_HUB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: logstash-configmap
                  key: ent-hub-endpoint
            - name: EVENT_HUB_CONNECTION_S
              valueFrom:
                secretKeyRef:
                  name: eventhub-pdi-02-string-key
                  key: EVENTHUB-PDI-02-STRING-KEY
            - name: STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: ekl-storage-acc-string-key
                  key: EKL-STORAGE-ACC-STRING-KEY
            - name: LOG_SPRING_JMS_LISTENER_RECEIVE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: logstash-configmap
                  key: log-spring-jms-listener-receive-timeout
            - name: LOG_SPRING_JMS_SERVICEBUS_PRICING_TIER
              valueFrom:
                configMapKeyRef:
                  name: logstash-configmap
                  key: log-spring-jms-servicebus-pricing-tier
            - name: LOG_SECRET_KEY_ENCRYPT_FIELDS
              valueFrom:
                secretKeyRef:
                  name: elastic-log-key
                  key: ELASTIC-LOG-KEY
            - name: LOG_NO_DOFILTER_EXECUTION
              valueFrom:
                configMapKeyRef:
                  name: ms-pendigital-configmap
                  key: log-no-dofilter-execution
            - name: LOG_LOGGING_FILTER_EXCLUDE
              valueFrom:
                configMapKeyRef:
                  name: ms-pendigital-configmap
                  key: log-logging-filter-exclude
            - name: PENDIG-NAME-STORAGE-ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: pendig-name-storage-account
                  key: PENDIG-NAME-STORAGE-ACCOUNT
            - name: PENDIG-CLIENT-ID-TOKEN
              valueFrom:
                secretKeyRef:
                  name: pendig-client-id-token
                  key: PENDIG-CLIENT-ID-TOKEN
            - name: PENDIG-CLIENT-SECRET-TOKEN
              valueFrom:
                secretKeyRef:
                  name: pendig-client-secret-token
                  key: PENDIG-CLIENT-SECRET-TOKEN
            - name: PENDIG-ID-TENANT
              valueFrom:
                secretKeyRef:
                  name: pendig-id-tenant
                  key: PENDIG-ID-TENANT
            - name: PENDIG-NAME-STORAGE-ONBOARDING
              valueFrom:
                secretKeyRef:
                  name: pendig-name-storage-onboarding
                  key: PENDIG-NAME-STORAGE-ONBOARDING
            - name: PENDIG-NAME-STORAGE-CUENTAS
              valueFrom:
                secretKeyRef:
                  name: pendig-name-storage-cuentas
                  key: PENDIG-NAME-STORAGE-CUENTAS
            - name: PENDIG-NAME-STORAGE-RECAUDOS
              valueFrom:
                secretKeyRef:
                  name: pendig-name-storage-recaudos
                  key: PENDIG-NAME-STORAGE-RECAUDOS
            - name: PENDIG-NAME-USERNAME-TOKEN
              valueFrom:
                secretKeyRef:
                  name: pendig-name-username-token
                  key: PENDIG-NAME-USERNAME-TOKEN
            - name: PENDIG-CLAVE-STORAGE-ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: pendig-clave-storage-account
                  key: PENDIG-CLAVE-STORAGE-ACCOUNT

---
apiVersion: v1
kind: Service
metadata:
  name: pendig-seguridad-ms-sas-generator-nodejs-services
  namespace: ns-pendigital-seguridad
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pendig-seguridad-ms-sas-generator-nodejs-deployment

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pendig-seguridad-ms-sas-generator-nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pendig-seguridad-ms-sas-generator-nodejs-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75
