export enum SasPermission {
  READ = 'r',
  WRITE = 'w',
  DELETE = 'd',
  LIST = 'l',
  ADD = 'a',
  CREATE = 'c',
  UPDATE = 'u',
  PROCESS = 'p',
  TAG = 't',
  FILTER = 'f',
  SET_IMMUTABILITY_POLICY = 'i',
  DELETE_VERSION = 'x',
  PERMANENT_DELETE = 'y',
  MOVE = 'm',
  EXECUTE = 'e',
  SET_PERMISSION = 'o',
  SET_OWNER = 'w',
}
